### ISSUE TITLE
Blocks does not load completely

### ISSUE THREAD

**Issue by KiarashN** [Equibit/explorer#38] opened 2018-12-11 18:48 UTC
It shows up to 448 but there are 565 blocks

![image.png](https://images.zenhubusercontent.com/5a5d26cd4b5806bc2bc2d766/d8a288f8-2f8a-41d9-b6cd-3a8f33fa7c77)

**Comment by Eternali** [comment] 2018-12-12 22:25
Since #25 this is not a problem. The root cause is addressed in #20 .

**Closed as completed by Eternali** 2018-12-12 22:26 UTC
